version: "3"

services:
  client:
    build: ./client
    container_name: baezijnismeemaken_client
    ports:
    - "3000:80"

  server:
    build: ./server
    container_name: baezijnismeemaken_server
    ports:
    - "8080:8080"
    environment:
    - "DATABASE_HOST=host.docker.internal"
