version: "3"

services:
  client:
    image: baezijnismeemaken_client
    container_name: baezijnismeemaken_client
    ports:
    - "3000:80"
    networks:
    - traefik_default
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.bae.rule=Host(`openluchtcantus.nl`)"
    - "traefik.http.routers.bae.entrypoints=websecure"
    - "traefik.http.routers.bae.tls.certresolver=myresolver"
    - "traefik.docker.network=traefik_default"

  server:
    image: baezijnismeemaken_server
    container_name: baezijnismeemaken_server
    ports:
    - "8080:8080"
    env_file:
    - ".env"
    environment:
    - "DATABASE_HOST=host.docker.internal"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    networks:
    - traefik_default
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.bae.rule=Host(`api.openluchtcantus.nl`)"
    - "traefik.http.routers.bae.entrypoints=websecure"
    - "traefik.http.routers.bae.tls.certresolver=myresolver"
    - "traefik.docker.network=traefik_default"

networks:
  traefik_default:
     external: true